/**
 * Connection Token Decoder
 *
 * Decodes `wmcp1_<base64>` tokens generated by the Axtolab AI Connector
 * admin panel. These tokens contain all credentials needed to configure
 * the MCP server without making any HTTP requests.
 *
 * @package axtolab-ai-connector
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface TokenPayload {
  v: number
  site_url: string
  base_url: string
  username: string
  token: string
  site_name: string
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const TOKEN_PREFIX = 'wmcp1_'

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Check whether a string looks like a connection token (starts with `wmcp1_`).
 */
export function isConnectionToken(input: string): boolean {
  return typeof input === 'string' && input.startsWith(TOKEN_PREFIX)
}

/**
 * Decode and validate a `wmcp1_<base64>` connection token.
 *
 * @throws {Error} if the token is malformed, has a bad prefix, or is missing
 *   required fields.
 */
export function decodeConnectionToken(tokenString: string): TokenPayload {
  if (!tokenString || !tokenString.startsWith(TOKEN_PREFIX)) {
    throw new Error(
      `Invalid connection token: must start with "${TOKEN_PREFIX}". ` +
        'Generate a new token from your WordPress admin panel.'
    )
  }

  const base64Part = tokenString.slice(TOKEN_PREFIX.length)

  if (!base64Part) {
    throw new Error('Invalid connection token: empty payload after prefix.')
  }

  let jsonString: string
  try {
    jsonString = Buffer.from(base64Part, 'base64').toString('utf-8')
  } catch {
    throw new Error(
      'Invalid connection token: could not decode base64 payload. ' +
        'The token may be corrupted — generate a new one.'
    )
  }

  let parsed: unknown
  try {
    parsed = JSON.parse(jsonString)
  } catch {
    throw new Error(
      'Invalid connection token: payload is not valid JSON. ' +
        'The token may be corrupted — generate a new one.'
    )
  }

  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
    throw new Error('Invalid connection token: payload must be a JSON object.')
  }

  const obj = parsed as Record<string, unknown>

  // Validate required fields
  const requiredStringFields = [
    'site_url',
    'base_url',
    'username',
    'token',
    'site_name',
  ] as const

  for (const field of requiredStringFields) {
    if (typeof obj[field] !== 'string' || !(obj[field] as string).trim()) {
      throw new Error(
        `Invalid connection token: missing or empty field "${field}".`
      )
    }
  }

  if (typeof obj['v'] !== 'number') {
    throw new Error(
      'Invalid connection token: missing or invalid version field "v".'
    )
  }

  if (obj['v'] !== 1) {
    throw new Error(
      `Unsupported token version ${String(obj['v'])}. ` +
        'You may need to download the latest Axtolab AI Connector desktop extension from WordPress Admin -> AI Connector.'
    )
  }

  // Validate URLs
  for (const urlField of ['site_url', 'base_url'] as const) {
    try {
      new URL(obj[urlField] as string)
    } catch {
      throw new Error(
        `Invalid connection token: "${urlField}" is not a valid URL.`
      )
    }
  }

  return {
    v: obj['v'] as number,
    site_url: obj['site_url'] as string,
    base_url: obj['base_url'] as string,
    username: obj['username'] as string,
    token: obj['token'] as string,
    site_name: obj['site_name'] as string,
  }
}
